"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ  # type: ignore

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # Allowed hosts for the Django app
    ALLOWED_HOSTS=(list[str], []),
    # Allowed origins for CORS
    ALLOWED_ORIGINS=(list[str], []),
    # Database host
    DB_HOST=(str, None),
    # Database name
    DB_NAME=(str, None),
    # Database password
    DB_PASSWORD=(str, None),
    # Database port
    DB_PORT=(int, None),
    # Database user
    DB_USER=(str, None),
    # Debug mode for Django
    DEBUG=(bool, False),
    # Secret key for Django
    DJANGO_SECRET_KEY=(
        str,
        "django-insecure-trkc%c14mv8b%95!spl5n&sg51f7wsyvasx%7ddl$07-f-iynh",
    ),
    # Key used for encrypting sensitive data
    ENCRYPTION_KEY=(str, None),
    # Frontend URL for the application
    FRONT_END_URL=(str, None),
    # Okta client ID
    OKTA_CLIENT_ID=(str, None),
    # Okta client secret
    OKTA_CLIENT_SECRET=(str, None),
    # Okta domain
    OKTA_DOMAIN=(str, None),
    # Okta login redirect URL
    OKTA_LOGIN_REDIRECT=(str, None),
    # Whether to run the application using HTTPS (affects secure cookies)
    USE_HTTPS=(bool, True),
)

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = env.str("DJANGO_SECRET_KEY")
DEBUG = env.bool("DEBUG")
ENCRYPTION_KEY = env.str("ENCRYPTION_KEY")

ALLOWED_HOSTS: list[str] = env.list("ALLOWED_HOSTS")

if "*" in env.list("ALLOWED_ORIGINS"):
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = env.list("ALLOWED_ORIGINS")

CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "core",
    "user",
    "rest_framework"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.auth.CustomAuthMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": env.str("DB_HOST"),
        "NAME": env.str("DB_NAME"),
        "USER": env.str("DB_USER"),
        "PASSWORD": env.str("DB_PASSWORD"),
        "PORT": env.int("DB_PORT"),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Auth config

AUTH_USER_MODEL = "core.User"

OKTA = {
    "DOMAIN": env.str("OKTA_DOMAIN"),
    "CLIENT_ID": env.str("OKTA_CLIENT_ID"),
    "CLIENT_SECRET": env.str("OKTA_CLIENT_SECRET"),
    "LOGIN_REDIRECT": env.str("OKTA_LOGIN_REDIRECT")
}

# Front-end config
FRONT_END_URL = env.str("FRONT_END_URL")

AUTH_COOKIE_CONFIG = {
    "NAME": "credentials",
    "DOMAIN": None,
    "SECURE": env.bool("USE_HTTPS"),
    "HTTP_ONLY": True,
    "PATH": "/",
    "SAMESITE": "Lax",
    "LIFETIME": timedelta(hours=1)
}

# Logging config

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}
