name: Check back-end
on:
  pull_request:
    branches:
      - main
    paths:
      - "back-end/**"

jobs:
  check-be:
    name: Check back-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end
    env:
      BUILD_ENV: production

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"
          cache: "pip"
          cache-dependency-path: |
            back-end/requirements.txt
            back-end/requirements.dev.txt
            back-end/requirements.test.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dev dependencies
        run: pip install -r requirements.dev.txt
      - name: Install test dependencies
        run: pip install -r requirements.test.txt
      - name: Lint with flake8
        run: flake8
      - name: Static type checking with mypy
        run: mypy . --strict
      - name: Test
        run: pytest
      - name: Build Docker image
        run: docker build .
