name: E2E tests
on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e-tests
    env:
      BUILD_ENV: production

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"
          cache: "pip"
          cache-dependency-path: e2e-tests/requirements.txt
      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('e2e-tests/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8
      - name: Static type checking with mypy
        run: mypy . --strict
      - name: Ensure browsers are installed
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: python -m playwright install --with-deps
      - name: Run your tests
        run: pytest --tracing=retain-on-failure
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
