name: E2E tests
on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e-tests
    env:
      BUILD_ENV: production

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
